blank_issues_enabled: false
contact_links:
    -   name: Questions & Discussions
        url: https://altiran.com/dev
        about: Use Altiran developer forum for message-board style questions and discussions.
