name: YT
on:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update latest YT Uploads
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get YT Videos
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          comment_tag_name: "YouTube"
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCQQrKnfeh1M8d6fZ7dSmxRQ"
